name: Build & Push Docker image to Docker HUB

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    name: Push to Docker HUB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Login to Docker HUB
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: brinth/esp8266_rtos_sdk

      - name: Build & Push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

